version: '3.4'
services:
  php:
      build: .
      volumes:
        - '.:/var/application'
      environment:
        - 'BRACKETS_SERVER_PORT=${BRACKETS_SERVER_PORT}'
      ports:
        - '${BRACKETS_SERVER_PORT}:${BRACKETS_SERVER_PORT}'
