services:
    # Socket
    socket:
        class: c3037\Otus\SecondWeek\BracketsServer\Socket\Service\Socket
        arguments:
            - '@bind_params_determinator'
            - '%max_concurrent_connections%'
        shared: false

    # Bind params determinator
    bind_params_determinator:
        class: c3037\Otus\SecondWeek\BracketsServer\Socket\Service\BindParamsDeterminator
        arguments:
            - '%host%'
            - '%port%'

    # Child process worker
    worker:
        class: c3037\Otus\SecondWeek\BracketsServer\Worker\Service\Worker
        arguments:
            - '@brackets_validation_processor'
            - '%quit_command%'
            - '%max_input_message_length%'

    # Brackets validation processor
    brackets_validation_processor:
        class: c3037\Otus\SecondWeek\BracketsServer\RequestProcessor\Service\BracketsValidationProcessor
        arguments:
            - '@brackets_validator'

    brackets_validator:
        class: c3037\Otus\FirstWeek\Library\Validator
        arguments:
            - '@ignored_char_container'
            - '@validation_pair_container'
            - '@opened_symbol_stack_factory'

    ignored_char_container:
        class: c3037\Otus\FirstWeek\Library\IgnoredChar\IgnoredCharContainer
        calls:
            -
              - 'add'
              -
                - '@space_char'
                - '@new_line_char'
                - '@carriage_return_char'
                - '@tabulation_char'
    space_char:
        class: c3037\Otus\FirstWeek\Library\IgnoredChar\IgnoredChar
        arguments:
            - ' '
    new_line_char:
        class: c3037\Otus\FirstWeek\Library\IgnoredChar\IgnoredChar
        arguments:
            - "\n"
    carriage_return_char:
        class: c3037\Otus\FirstWeek\Library\IgnoredChar\IgnoredChar
        arguments:
            - "\r"
    tabulation_char:
        class: c3037\Otus\FirstWeek\Library\IgnoredChar\IgnoredChar
        arguments:
            - "\t"

    validation_pair_container:
        class: c3037\Otus\FirstWeek\Library\ValidationPair\ValidationPairContainer
        calls:
            -
              - 'add'
              -
                - '@round_brackets'
    round_brackets:
        class: c3037\Otus\FirstWeek\Library\ValidationPair\ValidationPair
        arguments:
            - '('
            - ')'

    opened_symbol_stack_factory:
        class: c3037\Otus\FirstWeek\Library\OpenedSymbols\OpenedSymbolStackFactory
